name: build-and-test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker compose -f docker-compose.test.yml up -d
      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash
      - name: Test
        run: docker compose -f docker-compose.test.yml exec crzz mix test
      - name: Stop
        run: docker compose -f docker-compose.test.yml stop
